config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'notes#index'

  resources :notes do
   get :search, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  include PgSearch
  extend FriendlyId

  validates :title, :note, :status, presence: true

  STATUS = %w{ Alta Média Baixa }

  friendly_id :title, use: :slugged


  pg_search_scope :search,
   against: %i[title note status]

   def symbol
     case prioridade
     when 'Alta' then 'Prioridade Alta'
     when 'Média' then 'Prioridade Media'
     when 'Baixa' then 'Prioridade Baixa'
     end
   end

   def css_color
     case prioridade
     when 'Alta' then 'danger'
     when 'Média' then 'warning'
     when 'Baixa' then 'success'
     end
   end


  private

  def prioridade
    if status == 'Alta'
      'Alta'
    else
      if status == 'Média'
        'Média'
      else
        'Baixa'
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action  :authenticate_user!

  def index
    @notes = Note.all.order(created_at: :DESC)
  end

  def search
    @notes = Note.search(search_params[:q])
  end

  def show
  end

  def new
    @note = Note.new
  end

  def edit
  end


  def create
    @note = Note.new(note_params)

      if @note.save
       redirect_to @note, notice: 'Anotação criada com sucesso.'
      else
        flash.now[:alert] = @note.errors.full_messages.to_sentence
        render :new
      end
  end


  def update
    if @note.update(note_params)
      redirect_to @note, notice: 'Anotação atualizada com sucesso.'
    else
      flash.now[:alert] = @note.errors.full_messages.to_sentence
      render :edit
    end
  end


  def destroy
    @note.destroy
      redirect_to notes_url, notice: 'Anotação deletada com sucesso.'
  end

  private

  def set_note
    @note = Note.friendly.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :note, :data, :status)
  end

  def search_params
    params.permit(:q)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anotações</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-outline-info static-top mb-5">
      <div class="container">
        <% if user_signed_in? %>
          <%= link_to root_path, class: 'text-white btn btn-outline-info' do %>
            Anotações
          <% end %>
          <%= link_to "+ Anotações", new_note_path, class: 'btn btn-success' %>


      </div>

          <div class="dropdown-toggle text-right mr-4">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
        <% end %>
          </div>
    </nav>


      <main class="container">
        <% flash.each do |type, message| %>
          <div class="alert alert-<%= type == 'alert' ? 'danger' : 'success' %> alert-dismissible fade show" role="alert">
            <%= message %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>

      <% if user_signed_in? %>

        <div class="row">
          <div class="col-4 offset-8">
            <div class="search">
              <%= form_with url: search_notes_path, method: :get, local:true, class: 'form-inline' do |form| %>
                <div class="form-group mx-3 mb-3">
                  <%= form.search_field :q, class: 'form-control', required: true,
                  placeholder: 'Busca', value: params[:q] %>
                </div>
                <%= form.submit 'Buscar', class: 'btn btn-info mb-3', data: {disable_with: 'Buscando...'} %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
        <%= yield %>
      </main>


    <footer class='text-white text-center mt-5 p-8'>
      Copyright © Wendel Lopes <%= Date.current.year %>.
    </footer>

  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :note_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :note%>
    <%= form.text_area :note, id: :note_note, class: 'form-control', rows: 5 %>
  </div>

  <div class="form-group text-center">
    <%= form.label :data %>
    <%= form.datetime_select :data, id: :note_data %>
  </div>

  <div class="columns text-center">
    <div class="field column is-4">
      <div class="control">
        <%= form.label :status %>
        <div class="control has-icons-left">
          <span class="select">
            <%= form.select :status, Note::STATUS, id: :note_status %>
        </div>
      </div>
     </div>
  </div>

  <div class="mt-3 text-center">
    <%= form.submit 'Salvar', class: 'btn btn-success',
     data: { disable_with: 'Salvando...'} %>
  </div>

<% end %>

app/views/notes/_note.html.erb
<div class="card bg-light mb-3">
  <div class="card-body">
    <h4><%= link_to note.title, note %></h4>

    <div class="text-muted mb-2">
      <em>(<%= l note.created_at, format: :long %>)</em>

      <div class="text-right text-<%= note.css_color %>">
         <%= note.symbol %>
      </div>

    </div>

      <p><%= note.note.truncate(60) %></p>

      <%= link_to "Ver Anotação", note, class: 'btn btn-secondary' %>
      <%= link_to "Editar", edit_note_path(note), class: 'btn btn-warning' %>
      <%= link_to "Deletar",note, method: :delete, class: 'btn btn-danger',
      data: { confirm: 'Você tem certeza?'} %>
  </div>
</div>

app/views/notes/edit.html.erb
<div class="card bg-light mb-3">
  <div class="card-body">
    <h1>Editar Anotação</h1>

    <%= render 'form', note: @note %>
  </div>
</div>

app/views/notes/index.html.erb
<% @notes.each do |note| %>
  <%= render(note) %>
<% end %>

<hr>

app/views/notes/new.html.erb
<div class="card bg-light mb-3">
  <div class="card-body">
    <h1>Nova Anotação</h1>

    <%= render 'form', note: @note %>
  </div>  
</div>

app/views/notes/search.html.erb
  <h2 class="text-white">
    <% if @notes.any? %>
    <%= pluralize(@notes.count, 'Resultados') %> encontrados:
    <% else %>
    Nenhum resultado encontrado
    <% end %>
  </h2>


<% @notes.each do |note| %>
  <%= render note %>
<% end %>

app/views/notes/show.html.erb
<div class="shadow p-5 bg-white rounded">
  <div class="text-center">
    <h1 class="mb-4"><%= @note.title %></h1>
    <div class="text-right mb-4">Prioridade <%= @note.status %></div>
    <p class="text-muted">
      <%= @note.note.gsub("\n", "<br>").html_safe %>
    </p>

  </div>

  <hr>
  <%= l @note.created_at, format: :long %>
</div>